name: Setup
description: Install Bun and project dependencies.

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      shell: bash
      working-directory: installer-ts
      run: bun install
